{% set name = "modelscope" %}
{% set version = "1.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # The one on PyPI doesn't include setup.py.
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a11f1a98d31ff5b6c86598f80cf7e0ddc58be5c048e8e0309ed09f99a3f0b8de

build:
  number: 0
  noarch: python
  entry_points:
    - modelscope = modelscope.cli.cli:run_cmd
  script: |
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - filelock
    - requests >=2.25
    - tqdm >=4.64.0
  run:
    # We just include hub by default
    - python >={{ python_min }}
    - filelock  # Prevent import error
    - requests >=2.25
    - tqdm >=4.64.0
    - urllib3 >=1.26

test:
  imports:
    - modelscope
  commands:
    - pip check
    - modelscope --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/modelscope/modelscope
  summary: 'ModelScope: bring the notion of Model-as-a-Service to life.'
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - shermansiu
